Chore add batch call to get api/favorites
Azure-Samples/contoso-real-estate pull request #309
Opened 2023-08-26 10:10 UTC by GmausDev

I implement a batch call to the favorites call.

Now 
![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/3cb4fb64-1d95-4c78-a3a4-f891719f1931)

before 
![imagen](https://github.com/Azure-Samples/contoso-real-estate/assets/50465630/c07c4549-28ac-45dc-807e-9d3fd82802ee)

PD: Im not to much into ts or angular , so maybe can be a better way to do this or pattern I mean usually i work as BackEnd in another languages and im not feel confident at all with this solution . Im open to do this in a different way.  Just here to improve and learn 📟

2023-08-29 15:54 UTC, sinedied requested changes
Thanks for the PR!
Though this doesn't actually implement batching here, this debounces the call when the favorite button is clicked or initially loaded.

The initial solution using `ngOnChanges` is flawed as during the bootstrap phase of the page it's called multiple times, the debounce addition feels to me a bit like a bandaid on top of it, adding more complexity to a component that shouldn't bear this complexity in the first place.

I think that it might be better to move all the loading logic outside of this component entirely to implement proper batching in the parent component, but I'm ok with having this as a temporary fix if the few comments I put are fixed.

2023-08-29 15:54 UTC, sinedied commented on packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.ts
> +import { Subscription } from 'rxjs';
Could you merge the imports here?

2023-08-29 15:54 UTC, sinedied commented on packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.ts
> +          console.log(result);
Remove console.log

2023-08-30 06:48 UTC, GmausDev commented
Hi @sinedied  As I say im not was confident at all , tss is not my expertise 📎. I suppose there is a better solutions because as you say the `ngOnChanges` do his magic but im not understand at all how to work on this , so I googled solutions. There is no more time and I have been raised this on the discussion this Chore and maybe someone bring a better solution.

I´ll consider this like a small patch and expect a refactor :p 

Thank you for let me improve 😊

2023-08-30 13:56 UTC, sinedied submitted a review, later dismissed

2023-08-31 11:03 UTC, anfibiacreativa requested changes
Please approve formatting fixes

2023-08-31 11:07 UTC, GmausDev reviewed
👌

Hi @anfibiacreativa I'm looking , is @manekinekko who approves this?

2023-08-31 11:22 UTC, GmausDev commented
Umm , its done?
@anfibiacreativa  AzureDevOps its easier xD

2023-08-31 17:31 UTC, anfibiacreativa commented
> 👌
> 
> Hi @anfibiacreativa I'm looking , is @manekinekko who approves this?

Current maintainers of the repo are @manekinekko, @sinedied and myself.

2023-08-31 17:33 UTC, anfibiacreativa approved these changes

2023-08-31 17:34 UTC, merged