This pull request addresses issue #293, which was about the unequal sizes of listing cards on the homepage.
Azure-Samples/contoso-real-estate pull request #334
Opened 2023-09-06 11:39 UTC by alidotdeveloper

### **Changes Made:**
- Adjusted the CSS styles to ensure consistent card sizes.
- Aligned the titles and prices for a cleaner look.
-
**Testing Instructions:**
To test the changes, follow these steps:
- Go to homepage 
- scroll down to feature listings

 
**Related Issue:**
Closes #293

2023-09-07 08:46 UTC, manekinekko commented
Thank you @alidotdeveloper for these changes. Unfortunately, the fixed `.mat-mdc-card ` height breaks the RWD. Could you please make the size flexible?

![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/74404625-26df-481c-ab3d-115d2f8949a5)
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/f9f9f299-753d-4b6b-af79-84e69abae0ed)
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/1699357/afa08ab0-01d8-453c-af6c-de5ab85ccd55)

2023-09-07 16:16 UTC, alidotdeveloper commented
Sure

2023-09-07 18:02 UTC, alidotdeveloper commented
Fixed that issue, please check

2023-09-11 09:01 UTC, manekinekko requested changes

2023-09-11 09:01 UTC, manekinekko commented on package.json
>    }
can you revert these changes?

2023-09-11 09:02 UTC, manekinekko commented
The CSS change works like a charm! However, can you revert the npm changes? I don't think they were intended.

2023-09-22 15:52 UTC, closed without merging

2023-09-22 15:52 UTC, anfibiacreativa commented
@alidotdeveloper  Closing after two weeks of inactivity. Please let us know if you would like for us to reopen it!

2023-09-23 13:07 UTC, alidotdeveloper commented
Ops soory, I see that now I will fix it shortly

2023-09-23 19:43 UTC, alidotdeveloper commented
@manekinekko @anfibiacreativa I have open another pull request please check

2023-09-25 08:46 UTC, manekinekko commented
Hi @alidotdeveloper  I merged your other PR #293. Thank you :)