feat: comment feature for listings (redone to remove unnecessary changes😃)
Azure-Samples/contoso-real-estate pull request #336
Opened 2023-09-07 13:41 UTC by VictorCodebase

I have successfully managed to get back the version before the one with 185 files changed.

I have again really tried to see why 296 of listings.json is being flagged as changed. They are pretty much similar.
I even compared kinda literally:
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/0ec44f88-0544-4a26-9369-deb5ff22b356)

The code still runs as expected:
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/135356007/ed9bdd9a-16f1-4025-920f-4c3bbd63a457)

2023-09-12 13:18 UTC, manekinekko requested changes

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +  return user;
```suggestion
  return users[Math.floor(Math.random() * (users.length - 1))];
```

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +    return random;
```suggestion
    return Math.floor(Math.random() * max);
```

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +  return randomTime;
```suggestion
  return time[Math.floor(Math.random() * (time.length - 1))];
```

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +    return comment;
```suggestion
    return negative[Math.floor(Math.random() * (negative.length - 1))];
```

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +    return comment;
```suggestion
    return positive[Math.floor(Math.random() * (positive.length - 1))];
```

2023-09-12 13:18 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.ts
> +  dislikes: number[] = [];
can all of these be [Angular signals](https://angular.io/guide/signals)?

2023-09-13 07:12 UTC, VictorCodebase commented
Thanks so much @manekinekko for pointing out area I could improve. I really appreciate it thanks!

Ive incorporated the changes

2023-09-13 09:56 UTC, manekinekko requested changes

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.ts
> +  private route = inject(ActivatedRoute);
`route` is not used. You can remove it.

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.html
> +          <span>{{ comment }}</span>
```suggestion
          <span class="listing-comments__comment__body__text">{{ comment }}</span>
```

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.scss
> +        color: #999;
```suggestion
        color: #000;
```

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/comment-generator.ts
> +//import a way to get random numbers
can you convert this file into an [Angular service](https://angular.io/guide/architecture-services)?

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.ts
> +    //! I can revert it back if its better that way
you can remove this comment. The code below is more maintainable.

```suggestion
```

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.scss
> +
```suggestion
  & > div {
    width: 100%;
  }
```

2023-09-13 09:56 UTC, manekinekko commented on packages/portal/src/app/rentalpage/rentalpage.component.scss
> +    width: 730px;
```suggestion
```

2023-09-14 04:22 UTC, VictorCodebase commented
Im so excited to say that Ive managed to make all improvements suggested - including the changing comment-generator file to Angular service one.

2023-10-18 10:09 UTC, closed without merging

2023-10-22 17:57 UTC, VictorCodebase commented
Thank you so much @anfibiacreativa , @manekinekko and @sinedied  for taking us through the hackathon. I really learnt a lot to do with collaboration, using GitHub, Copilot, using Azure, using JS frameworks like azure (I never knew what to learn) and like so so much more.

I couldn't be more grateful😀